name: meta_weather
description: A command-line application to display weather by chosen location.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
   http: ^0.13.5
   intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0